name: Docs

on:
  push:
    branches:
      - main
    paths:
      - "*.tf"

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: terraform-docs/gh-actions@v1
        with:
          output-file: README.md
          output-method: inject
          git-push: "true"
